## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName

    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

    def __iadd__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov + v)

    def __isub__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov - v)

    def __imul__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov * v)

    def __idiv__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov / v)

    def __iand__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov & v)

    def __ior__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov | v)

    def __ixor__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov ^ v)

class _ARRW:
    def __init__(self, obj, index):
        self.obj = obj
        self.index = index

    def __lshift__(self, r):
        self.obj[self.index] = r

    def __iadd__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov + v

    def __isub__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov - v

    def __imul__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov * v

    def __idiv__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov / v

    def __iand__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov & v

    def __ior__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov | v

    def __ixor__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov ^ v

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v.makeL() if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) import Header;
import Header
# (Line 2) import Map;
import Map
# (Line 3) import Player;
import Player
# (Line 4) import Helpers;
import Helpers
# (Line 6) const BombQ						= EUDArray(20);
BombQ = _CGFW(lambda: [EUDArray(20)], 1)[0]
# (Line 7) var QIndex, QCount, boom;
QIndex, QCount, boom = EUDCreateVariables(3)
# (Line 9) const row						= Map.row;
row = _CGFW(lambda: [Map.row], 1)[0]
# (Line 10) const col						= Map.col;
col = _CGFW(lambda: [Map.col], 1)[0]
# (Line 11) const scale						= Map.scale;
scale = _CGFW(lambda: [Map.scale], 1)[0]
# (Line 13) const Computer					= Header.Computer;
Computer = _CGFW(lambda: [Header.Computer], 1)[0]
# (Line 14) const UnitID_Player 			= Header.UnitID_Player;
UnitID_Player = _CGFW(lambda: [Header.UnitID_Player], 1)[0]
# (Line 15) const UnitID_Bomb				= Header.UnitID_Bomb;
UnitID_Bomb = _CGFW(lambda: [Header.UnitID_Bomb], 1)[0]
# (Line 16) const UnitID_Fire				= Header.UnitID_Fire;
UnitID_Fire = _CGFW(lambda: [Header.UnitID_Fire], 1)[0]
# (Line 17) const UnitID_Wall				= Header.UnitID_Wall;
UnitID_Wall = _CGFW(lambda: [Header.UnitID_Wall], 1)[0]
# (Line 18) const UnitID_Box				= Header.UnitID_Box;
UnitID_Box = _CGFW(lambda: [Header.UnitID_Box], 1)[0]
# (Line 19) const DeadBox					= Header.DeadBox;
DeadBox = _CGFW(lambda: [Header.DeadBox], 1)[0]
# (Line 20) const ItemList					= Header.ItemList;
ItemList = _CGFW(lambda: [Header.ItemList], 1)[0]
# (Line 22) const loc2 = $L('loc2');
loc2 = _CGFW(lambda: [GetLocationIndex('loc2')], 1)[0]
# (Line 23) const loc3 = $L('loc3');
loc3 = _CGFW(lambda: [GetLocationIndex('loc3')], 1)[0]
# (Line 26) function NewBomb(unitEpd)
# (Line 27) {
@EUDFunc
def NewBomb(unitEpd):
    # (Line 28) const x, y = Map.GetTileIndex(unitEpd);
    x, y = List2Assignable([Map.GetTileIndex(unitEpd)])
    # (Line 29) Map.SetMapXY(x, y, unitEpd);
    Map.SetMapXY(x, y, unitEpd)
    # (Line 30) }
    # (Line 32) function Push(unitEpd)

# (Line 33) {
@EUDFunc
def Push(unitEpd):
    # (Line 34) BombQ[QIndex] = unitEpd;
    _ARRW(BombQ, QIndex) << (unitEpd)
    # (Line 35) QIndex = QIndex + 1; //Index ++
    QIndex << (QIndex + 1)
    # (Line 36) QCount = QCount + 1; //Count ++
    QCount << (QCount + 1)
    # (Line 37) }
    # (Line 38) function InitQ()

# (Line 39) {
@EUDFunc
def InitQ():
    # (Line 40) for(var i=0; i<20; i++)
    i = EUDVariable()
    i << (0)
    if EUDWhile()(i >= 20, neg=True):
        def _t2():
            i.__iadd__(1)
        # (Line 41) BombQ[i] = 0;
        _ARRW(BombQ, i) << (0)
        # (Line 42) QIndex = 0;
        EUDSetContinuePoint()
        _t2()
    EUDEndWhile()
    QIndex << (0)
    # (Line 43) QCount = 0;
    QCount << (0)
    # (Line 44) }
    # (Line 46) function CreateItem(location);

# (Line 47) function Explosion(unitEpd);
# (Line 48) function CreateFire(fireRange, direction, _x, _y);
# (Line 49) function Boom();
# (Line 52) function CheckBomb()
# (Line 53) {//Check bombs' counter at map, Start of explosion. 맵의 모든 폭탄 시간 체크
@EUDFunc
def CheckBomb():
    # (Line 54) for(var i=0; i<row; i++)
    i = EUDVariable()
    i << (0)
    if EUDWhile()(i >= row, neg=True):
        def _t2():
            i.__iadd__(1)
        # (Line 55) {
        # (Line 56) for(var j=0; j<col; j++)
        j = EUDVariable()
        j << (0)
        if EUDWhile()(j >= col, neg=True):
            def _t4():
                j.__iadd__(1)
            # (Line 57) {
            # (Line 58) const unitEpd = Map.GetMapXY(i, j);
            unitEpd = Map.GetMapXY(i, j)
            # (Line 59) if( unitEpd != 0 ||
            _t5 = EUDIf()
            # (Line 60) unitEpd != UnitID_Fire ||
            # (Line 61) unitEpd != UnitID_Box ||
            # (Line 62) unitEpd != UnitID_Wall)
            if _t5(EUDSCOr()(unitEpd == 0, neg=True)(unitEpd == UnitID_Fire, neg=True)(unitEpd == UnitID_Box, neg=True)(unitEpd == UnitID_Wall, neg=True)()):
                # (Line 63) {
                # (Line 64) if(MemoryEPD(unitEpd + 0x114/4, Exactly, 1))
                if EUDIf()(MemoryEPD(unitEpd + 0x114 // 4, Exactly, 1)):
                    # (Line 65) {
                    # (Line 66) Push(unitEpd);
                    Push(unitEpd)
                    # (Line 67) }
                    # (Line 68) }
                EUDEndIf()
                # (Line 69) }
            EUDEndIf()
            # (Line 70) }
            EUDSetContinuePoint()
            _t4()
        EUDEndWhile()
        # (Line 71) var k = 0;
        EUDSetContinuePoint()
        _t2()
    EUDEndWhile()
    k = EUDVariable()
    k << (0)
    # (Line 72) while(QCount > 0) //Count > 0
    if EUDWhile()(QCount <= 0, neg=True):
        # (Line 73) {
        # (Line 74) Explosion(BombQ[k]);
        Explosion(BombQ[k])
        # (Line 75) k++;
        k.__iadd__(1)
        # (Line 76) QCount = QCount - 1; // Count--
        QCount << (QCount - 1)
        # (Line 77) }
        # (Line 78) if(QIndex > 0)
    EUDEndWhile()
    if EUDIf()(QIndex <= 0, neg=True):
        # (Line 79) {
        # (Line 80) Boom();
        Boom()
        # (Line 81) InitQ();
        InitQ()
        # (Line 82) }
        # (Line 83) }
    EUDEndIf()
    # (Line 85) function Boom()

# (Line 86) {// Compute checked blocks, actually explosion 체크한 블록을 처리함. 실질적인 폭발
@EUDFunc
def Boom():
    # (Line 87) boom = 1;
    boom << (1)
    # (Line 88) for(var i=0; i<row; i++)
    i = EUDVariable()
    i << (0)
    if EUDWhile()(i >= row, neg=True):
        def _t2():
            i.__iadd__(1)
        # (Line 89) {
        # (Line 90) for(var j=0; j<col; j++)
        j = EUDVariable()
        j << (0)
        if EUDWhile()(j >= col, neg=True):
            def _t4():
                j.__iadd__(1)
            # (Line 91) {
            # (Line 92) if(Map.GetMapXY(i, j) == UnitID_Fire)
            if EUDIf()(Map.GetMapXY(i, j) == UnitID_Fire):
                # (Line 93) {
                # (Line 94) Map.SetMapXY(i, j, 0);
                Map.SetMapXY(i, j, 0)
                # (Line 95) const x, y = Map.GetTileXY(i, j);
                x, y = List2Assignable([Map.GetTileXY(i, j)])
                # (Line 96) Helpers.EUDSetLocation(loc2, x, y);
                Helpers.EUDSetLocation(loc2, x, y)
                # (Line 97) KillUnitAt(All, '(men)', loc2+1, $Force1);
                DoActions(KillUnitAt(All, '(men)', loc2 + 1, 18))
                # (Line 98) RemoveUnitAt(All, '(any unit)', loc2+1, Computer);
                DoActions(RemoveUnitAt(All, '(any unit)', loc2 + 1, Computer))
                # (Line 99) CreateUnit(1, UnitID_Fire, loc2+1, Computer);
                DoActions(CreateUnit(1, UnitID_Fire, loc2 + 1, Computer))
                # (Line 100) }
                # (Line 101) if(Map.GetMapXY(i, j) == DeadBox)
            EUDEndIf()
            if EUDIf()(Map.GetMapXY(i, j) == DeadBox):
                # (Line 102) {
                # (Line 103) Map.SetMapXY(i, j, 0);
                Map.SetMapXY(i, j, 0)
                # (Line 104) const x, y = Map.GetTileXY(i, j);
                x, y = List2Assignable([Map.GetTileXY(i, j)])
                # (Line 105) Helpers.EUDSetLocation(loc2, x, y);
                Helpers.EUDSetLocation(loc2, x, y)
                # (Line 106) RemoveUnitAt(All, '(men)', loc2+1, Computer);
                DoActions(RemoveUnitAt(All, '(men)', loc2 + 1, Computer))
                # (Line 107) CreateItem(loc2);
                CreateItem(loc2)
                # (Line 108) }
                # (Line 109) }
            EUDEndIf()
            # (Line 110) }
            EUDSetContinuePoint()
            _t4()
        EUDEndWhile()
        # (Line 111) KillUnit(UnitID_Fire, Computer);
        EUDSetContinuePoint()
        _t2()
    EUDEndWhile()
    DoActions(KillUnit(UnitID_Fire, Computer))
    # (Line 112) boom = 0;
    boom << (0)
    # (Line 113) }
    # (Line 115) function Explosion(unitEpd)

# (Line 116) {// Create fire by its range 폭탄 사거리에 맞게 불 생성
@EUDFunc
def Explosion(unitEpd):
    # (Line 117) const player = Helpers.GetPlayerID(unitEpd);
    player = Helpers.GetPlayerID(unitEpd)
    # (Line 118) const fireRange = Player.GetRangeAtBomb(unitEpd);
    fireRange = Player.GetRangeAtBomb(unitEpd)
    # (Line 120) const x, y = Map.GetTileIndex(unitEpd); // 해당좌표의 unitEpd
    x, y = List2Assignable([Map.GetTileIndex(unitEpd)])
    # (Line 121) Map.SetMapXY(x, y, 0);  // 초기화
    Map.SetMapXY(x, y, 0)
    # (Line 123) const x2, y2 = Map.GetTileXY(x, y);
    x2, y2 = List2Assignable([Map.GetTileXY(x, y)])
    # (Line 124) Helpers.EUDSetLocation(loc2, x2, y2);
    Helpers.EUDSetLocation(loc2, x2, y2)
    # (Line 125) RemoveUnitAt(1, UnitID_Bomb, loc2+1, player);
    DoActions(RemoveUnitAt(1, UnitID_Bomb, loc2 + 1, player))
    # (Line 127) for(var i=0; i<4; i++)
    i = EUDVariable()
    i << (0)
    if EUDWhile()(i >= 4, neg=True):
        def _t2():
            i.__iadd__(1)
        # (Line 128) {
        # (Line 129) CreateFire(fireRange, i, x, y);
        CreateFire(fireRange, i, x, y)
        # (Line 130) }
        # (Line 131) }
        EUDSetContinuePoint()
        _t2()
    EUDEndWhile()
    # (Line 135) function CreateFire(fireRange, direction, _x, _y)

# (Line 136) {// 불 생성 지역에, 있는 지형/폭탄 탐지
@EUDFunc
def CreateFire(fireRange, direction, _x, _y):
    # (Line 137) Map.SetMapXY(_x, _y, UnitID_Fire);
    Map.SetMapXY(_x, _y, UnitID_Fire)
    # (Line 138) for(var j=1; j<=fireRange; j++)
    j = EUDVariable()
    j << (1)
    if EUDWhile()(j <= fireRange):
        def _t2():
            j.__iadd__(1)
        # (Line 139) {
        # (Line 140) var x = _x;
        x = EUDVariable()
        x << (_x)
        # (Line 141) var y = _y;
        y = EUDVariable()
        y << (_y)
        # (Line 143) if(direction == 0)
        if EUDIf()(direction == 0):
            # (Line 144) {
            # (Line 145) if(x < j) x = 0;
            if EUDIf()(x >= j, neg=True):
                x << (0)
                # (Line 146) else x = x - j;
            if EUDElse()():
                x << (x - j)
                # (Line 147) }
            EUDEndIf()
            # (Line 148) if(direction == 1)
        EUDEndIf()
        if EUDIf()(direction == 1):
            # (Line 149) {
            # (Line 150) if(y < j) y = 0;
            if EUDIf()(y >= j, neg=True):
                y << (0)
                # (Line 151) else y = y - j;
            if EUDElse()():
                y << (y - j)
                # (Line 152) }
            EUDEndIf()
            # (Line 153) if(direction == 2)
        EUDEndIf()
        if EUDIf()(direction == 2):
            # (Line 154) {
            # (Line 155) if(x + j > row) x = row;
            if EUDIf()(x + j <= row, neg=True):
                x << (row)
                # (Line 156) else x = x + j;
            if EUDElse()():
                x << (x + j)
                # (Line 157) }
            EUDEndIf()
            # (Line 158) if(direction == 3)
        EUDEndIf()
        if EUDIf()(direction == 3):
            # (Line 159) {
            # (Line 160) if(y + j > col) y = col;
            if EUDIf()(y + j <= col, neg=True):
                y << (col)
                # (Line 161) else y = y + j;
            if EUDElse()():
                y << (y + j)
                # (Line 162) }
            EUDEndIf()
            # (Line 164) if (Map.GetMapXY(x, y) == UnitID_Wall) return;	// Imapssible
        EUDEndIf()
        if EUDIf()(Map.GetMapXY(x, y) == UnitID_Wall):
            EUDReturn()
            # (Line 165) else if (Map.GetMapXY(x, y) == UnitID_Fire) 	// Fire
        if EUDElseIf()(Map.GetMapXY(x, y) == UnitID_Fire):
            # (Line 166) Map.SetMapXY(x, y, UnitID_Fire);
            Map.SetMapXY(x, y, UnitID_Fire)
            # (Line 167) else if (Map.GetMapXY(x, y) == 0) 				// Empty
        if EUDElseIf()(Map.GetMapXY(x, y) == 0):
            # (Line 168) Map.SetMapXY(x, y, UnitID_Fire);
            Map.SetMapXY(x, y, UnitID_Fire)
            # (Line 169) else if (Map.GetMapXY(x, y) == UnitID_Box) 		// Breakable
        if EUDElseIf()(Map.GetMapXY(x, y) == UnitID_Box):
            # (Line 170) {
            # (Line 171) Map.SetMapXY(x, y, DeadBox);
            Map.SetMapXY(x, y, DeadBox)
            # (Line 172) return;
            EUDReturn()
            # (Line 173) }
            # (Line 174) else if (Map.GetMapXY(x, y) == DeadBox) return;
        if EUDElseIf()(Map.GetMapXY(x, y) == DeadBox):
            EUDReturn()
            # (Line 175) else 											// bomb (unitEpd)
            # (Line 176) {
        if EUDElse()():
            # (Line 177) const unitEpd = Map.GetMapXY(x, y);
            unitEpd = Map.GetMapXY(x, y)
            # (Line 178) Push(unitEpd);
            Push(unitEpd)
            # (Line 179) }
            # (Line 180) }
        EUDEndIf()
        # (Line 181) }
        EUDSetContinuePoint()
        _t2()
    EUDEndWhile()
    # (Line 183) function CreateItem(location)

# (Line 184) {
@EUDFunc
def CreateItem(location):
    # (Line 185) if(Helpers.GetRandom(0,2))// 0~1
    if EUDIf()(Helpers.GetRandom(0, 2)):
        # (Line 186) {
        # (Line 187) const randNum = Helpers.GetRandom(0, 9)%6; //0~8 -> 0~5
        randNum = Helpers.GetRandom(0, 9) % 6
        # (Line 188) CreateUnit(1, ItemList[randNum], location +1, Computer);
        DoActions(CreateUnit(1, ItemList[randNum], location + 1, Computer))
        # (Line 189) }
        # (Line 190) }
    EUDEndIf()
