## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName

    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

    def __iadd__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov + v)

    def __isub__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov - v)

    def __imul__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov * v)

    def __idiv__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov / v)

    def __iand__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov & v)

    def __ior__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov | v)

    def __ixor__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov ^ v)

class _ARRW:
    def __init__(self, obj, index):
        self.obj = obj
        self.index = index

    def __lshift__(self, r):
        self.obj[self.index] = r

    def __iadd__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov + v

    def __isub__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov - v

    def __imul__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov * v

    def __idiv__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov / v

    def __iand__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov & v

    def __ior__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov | v

    def __ixor__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov ^ v

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v.makeL() if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) import Header;
import Header
# (Line 2) import Map;
import Map
# (Line 3) import Player;
import Player
# (Line 4) import Helpers;
import Helpers
# (Line 6) const BombQ						= EUDArray(20);
BombQ = _CGFW(lambda: [EUDArray(20)], 1)[0]
# (Line 7) var QIndex, QCount, boom;
QIndex, QCount, boom = EUDCreateVariables(3)
# (Line 9) const row						= Map.row;
row = _CGFW(lambda: [Map.row], 1)[0]
# (Line 10) const col						= Map.col;
col = _CGFW(lambda: [Map.col], 1)[0]
# (Line 11) const scale						= Map.scale;
scale = _CGFW(lambda: [Map.scale], 1)[0]
# (Line 13) const Computer					= Header.Computer;
Computer = _CGFW(lambda: [Header.Computer], 1)[0]
# (Line 14) const UnitID_Player 			= Header.UnitID_Player;
UnitID_Player = _CGFW(lambda: [Header.UnitID_Player], 1)[0]
# (Line 15) const UnitID_Bomb				= Header.UnitID_Bomb;
UnitID_Bomb = _CGFW(lambda: [Header.UnitID_Bomb], 1)[0]
# (Line 16) const UnitID_Fire				= Header.UnitID_Fire;
UnitID_Fire = _CGFW(lambda: [Header.UnitID_Fire], 1)[0]
# (Line 17) const UnitID_Wall				= Header.UnitID_Wall;
UnitID_Wall = _CGFW(lambda: [Header.UnitID_Wall], 1)[0]
# (Line 18) const UnitID_Box				= Header.UnitID_Box;
UnitID_Box = _CGFW(lambda: [Header.UnitID_Box], 1)[0]
# (Line 19) const DeadBox					= Header.DeadBox;
DeadBox = _CGFW(lambda: [Header.DeadBox], 1)[0]
# (Line 20) const ItemList					= Header.ItemList;
ItemList = _CGFW(lambda: [Header.ItemList], 1)[0]
# (Line 22) const loc2 = $L('loc2');
loc2 = _CGFW(lambda: [GetLocationIndex('loc2')], 1)[0]
# (Line 23) const loc3 = $L('loc3');
loc3 = _CGFW(lambda: [GetLocationIndex('loc3')], 1)[0]
# (Line 26) function NewBomb(unitEpd)
# (Line 27) {
@EUDFunc
def NewBomb(unitEpd):
    # (Line 28) const x, y = Map.GetTileIndex(unitEpd);
    x, y = List2Assignable([Map.GetTileIndex(unitEpd)])
    # (Line 29) Map.SetMapXY(x, y, unitEpd);
    Map.SetMapXY(x, y, unitEpd)
    # (Line 30) }
    # (Line 32) function Push(unitEpd)

# (Line 33) {
@EUDFunc
def Push(unitEpd):
    # (Line 34) BombQ[QIndex] = unitEpd;
    _ARRW(BombQ, QIndex) << (unitEpd)
    # (Line 35) QIndex = QIndex + 1; //Index ++
    QIndex << (QIndex + 1)
    # (Line 36) QCount = QCount + 1; //Count ++
    QCount << (QCount + 1)
    # (Line 37) }
    # (Line 38) function InitQ()

# (Line 39) {
@EUDFunc
def InitQ():
    # (Line 40) for(var i=0; i<20; i++)
    i = EUDVariable()
    i << (0)
    if EUDWhile()(i >= 20, neg=True):
        def _t2():
            i.__iadd__(1)
        # (Line 41) BombQ[i] = 0;
        _ARRW(BombQ, i) << (0)
        # (Line 42) QIndex = 0;
        EUDSetContinuePoint()
        _t2()
    EUDEndWhile()
    QIndex << (0)
    # (Line 43) QCount = 0;
    QCount << (0)
    # (Line 44) }
    # (Line 46) function CreateItem(location);

# (Line 47) function Explosion(unitEpd);
# (Line 48) function CreateFire(fireRange, direction, _x, _y);
# (Line 49) function Boom();
# (Line 50) function BombWayBlock(unitEpd);
# (Line 52) function CheckBomb()
# (Line 53) {//Check bombs' counter at map, Start of explosion. 맵의 모든 폭탄 시간 체크
@EUDFunc
def CheckBomb():
    # (Line 54) for(var i=0; i<row; i++)
    i = EUDVariable()
    i << (0)
    if EUDWhile()(i >= row, neg=True):
        def _t2():
            i.__iadd__(1)
        # (Line 55) {
        # (Line 56) for(var j=0; j<col; j++)
        j = EUDVariable()
        j << (0)
        if EUDWhile()(j >= col, neg=True):
            def _t4():
                j.__iadd__(1)
            # (Line 57) {
            # (Line 58) const unitEpd = Map.GetMapXY(i, j);
            unitEpd = Map.GetMapXY(i, j)
            # (Line 59) if( unitEpd != 0 ||
            _t5 = EUDIf()
            # (Line 60) unitEpd != UnitID_Fire ||
            # (Line 61) unitEpd != UnitID_Box ||
            # (Line 62) unitEpd != UnitID_Wall)
            if _t5(EUDSCOr()(unitEpd == 0, neg=True)(unitEpd == UnitID_Fire, neg=True)(unitEpd == UnitID_Box, neg=True)(unitEpd == UnitID_Wall, neg=True)()):
                # (Line 63) {
                # (Line 64) if(MemoryEPD(unitEpd + 0x114/4, Exactly, 1))
                if EUDIf()(MemoryEPD(unitEpd + 0x114 // 4, Exactly, 1)):
                    # (Line 65) {//timer is 1(0)
                    # (Line 66) Push(unitEpd);
                    Push(unitEpd)
                    # (Line 67) }
                    # (Line 68) BombWayBlock(unitEpd);
                EUDEndIf()
                BombWayBlock(unitEpd)
                # (Line 69) }
                # (Line 70) }
            EUDEndIf()
            # (Line 71) }
            EUDSetContinuePoint()
            _t4()
        EUDEndWhile()
        # (Line 72) var k = 0;
        EUDSetContinuePoint()
        _t2()
    EUDEndWhile()
    k = EUDVariable()
    k << (0)
    # (Line 73) while(QCount > 0) //Count > 0
    if EUDWhile()(QCount <= 0, neg=True):
        # (Line 74) {
        # (Line 75) Explosion(BombQ[k]);
        Explosion(BombQ[k])
        # (Line 76) k++;
        k.__iadd__(1)
        # (Line 77) QCount = QCount - 1; // Count--
        QCount << (QCount - 1)
        # (Line 78) }
        # (Line 79) if(QIndex > 0)
    EUDEndWhile()
    if EUDIf()(QIndex <= 0, neg=True):
        # (Line 80) {
        # (Line 81) Boom();
        Boom()
        # (Line 82) InitQ();
        InitQ()
        # (Line 83) }
        # (Line 84) }
    EUDEndIf()
    # (Line 86) function BombWayBlock(unitEpd)

# (Line 87) {
@EUDFunc
def BombWayBlock(unitEpd):
    # (Line 88) if(Player.IsBombWayBlocked(unitEpd) == 0)
    if EUDIf()(Player.IsBombWayBlocked(unitEpd) == 0):
        # (Line 89) {// bomb way block
        # (Line 90) const i, j = Map.GetTileIndex(unitEpd);
        i, j = List2Assignable([Map.GetTileIndex(unitEpd)])
        # (Line 91) var bool = 0;
        bool = EUDVariable()
        bool << (0)
        # (Line 92) EUDPlayerLoop()();
        EUDPlayerLoop()()
        # (Line 93) const player = getcurpl();
        player = f_getcurpl()
        # (Line 94) const px, py = Map.GetTileIndex(Player.GetPlayerEpd(player));
        px, py = List2Assignable([Map.GetTileIndex(Player.GetPlayerEpd(player))])
        # (Line 95) if(px == i && py == j)
        if EUDIf()(EUDSCAnd()(px == i)(py == j)()):
            # (Line 96) {// player is on bomb
            # (Line 97) bool = 1;
            bool << (1)
            # (Line 98) }
            # (Line 99) EUDEndPlayerLoop();
        EUDEndIf()
        EUDEndPlayerLoop()
        # (Line 100) if(bool == 0)
        if EUDIf()(bool == 0):
            # (Line 101) {// no one is on bomb
            # (Line 102) Player.SetBombWayBlock(unitEpd, 1);
            Player.SetBombWayBlock(unitEpd, 1)
            # (Line 103) const x, y = Map.GetTileXY(i, j);
            x, y = List2Assignable([Map.GetTileXY(i, j)])
            # (Line 104) Helpers.EUDSetLocation(loc2, x, y);
            Helpers.EUDSetLocation(loc2, x, y)
            # (Line 105) CreateUnit(1, 129, loc2+1, Computer); //way blocker
            DoActions(CreateUnit(1, 129, loc2 + 1, Computer))
            # (Line 106) }
            # (Line 107) }
        EUDEndIf()
        # (Line 108) }
    EUDEndIf()
    # (Line 109) function Boom()

# (Line 110) {// Check explosion blocks, actual explosion 체크한 블록을 처리함. 실질적인 폭발
@EUDFunc
def Boom():
    # (Line 111) boom = 1;
    boom << (1)
    # (Line 112) for(var i=0; i<row; i++)
    i = EUDVariable()
    i << (0)
    if EUDWhile()(i >= row, neg=True):
        def _t2():
            i.__iadd__(1)
        # (Line 113) {
        # (Line 114) for(var j=0; j<col; j++)
        j = EUDVariable()
        j << (0)
        if EUDWhile()(j >= col, neg=True):
            def _t4():
                j.__iadd__(1)
            # (Line 115) {
            # (Line 116) if(Map.GetMapXY(i, j) == UnitID_Fire)
            if EUDIf()(Map.GetMapXY(i, j) == UnitID_Fire):
                # (Line 117) {
                # (Line 118) Map.SetMapXY(i, j, 0);
                Map.SetMapXY(i, j, 0)
                # (Line 119) const x, y = Map.GetTileXY(i, j);
                x, y = List2Assignable([Map.GetTileXY(i, j)])
                # (Line 120) Helpers.EUDSetLocation(loc2, x, y);
                Helpers.EUDSetLocation(loc2, x, y)
                # (Line 121) KillUnitAt(All, '(men)', loc2+1, $Force1);
                DoActions(KillUnitAt(All, '(men)', loc2 + 1, 18))
                # (Line 122) RemoveUnitAt(All, '(any unit)', loc2+1, Computer);
                DoActions(RemoveUnitAt(All, '(any unit)', loc2 + 1, Computer))
                # (Line 123) CreateUnit(1, UnitID_Fire, loc2+1, Computer);
                DoActions(CreateUnit(1, UnitID_Fire, loc2 + 1, Computer))
                # (Line 124) }
                # (Line 125) if(Map.GetMapXY(i, j) == DeadBox)
            EUDEndIf()
            if EUDIf()(Map.GetMapXY(i, j) == DeadBox):
                # (Line 126) {
                # (Line 127) Map.SetMapXY(i, j, 0);
                Map.SetMapXY(i, j, 0)
                # (Line 128) const x, y = Map.GetTileXY(i, j);
                x, y = List2Assignable([Map.GetTileXY(i, j)])
                # (Line 129) Helpers.EUDSetLocation(loc2, x, y);
                Helpers.EUDSetLocation(loc2, x, y)
                # (Line 130) RemoveUnitAt(All, '(men)', loc2+1, Computer);
                DoActions(RemoveUnitAt(All, '(men)', loc2 + 1, Computer))
                # (Line 131) CreateItem(loc2);
                CreateItem(loc2)
                # (Line 132) }
                # (Line 133) }
            EUDEndIf()
            # (Line 134) }
            EUDSetContinuePoint()
            _t4()
        EUDEndWhile()
        # (Line 135) KillUnit(UnitID_Fire, Computer);
        EUDSetContinuePoint()
        _t2()
    EUDEndWhile()
    DoActions(KillUnit(UnitID_Fire, Computer))
    # (Line 136) RemoveUnit(129, Computer);
    DoActions(RemoveUnit(129, Computer))
    # (Line 137) boom = 0;
    boom << (0)
    # (Line 138) }
    # (Line 140) function Explosion(unitEpd)

# (Line 141) {// Create fire by its range 폭탄 사거리에 맞게 불 생성
@EUDFunc
def Explosion(unitEpd):
    # (Line 142) const player = Helpers.GetPlayerID(unitEpd);
    player = Helpers.GetPlayerID(unitEpd)
    # (Line 143) const fireRange = Player.GetRangeAtBomb(unitEpd);
    fireRange = Player.GetRangeAtBomb(unitEpd)
    # (Line 145) const x, y = Map.GetTileIndex(unitEpd); // 해당좌표의 unitEpd
    x, y = List2Assignable([Map.GetTileIndex(unitEpd)])
    # (Line 146) Map.SetMapXY(x, y, 0);  // 초기화
    Map.SetMapXY(x, y, 0)
    # (Line 148) const x2, y2 = Map.GetTileXY(x, y);
    x2, y2 = List2Assignable([Map.GetTileXY(x, y)])
    # (Line 149) Helpers.EUDSetLocation(loc2, x2, y2);
    Helpers.EUDSetLocation(loc2, x2, y2)
    # (Line 150) RemoveUnitAt(1, UnitID_Bomb, loc2+1, player);
    DoActions(RemoveUnitAt(1, UnitID_Bomb, loc2 + 1, player))
    # (Line 152) for(var i=0; i<4; i++)
    i = EUDVariable()
    i << (0)
    if EUDWhile()(i >= 4, neg=True):
        def _t2():
            i.__iadd__(1)
        # (Line 153) {
        # (Line 154) CreateFire(fireRange, i, x, y);
        CreateFire(fireRange, i, x, y)
        # (Line 155) }
        # (Line 156) }
        EUDSetContinuePoint()
        _t2()
    EUDEndWhile()
    # (Line 160) function CreateFire(fireRange, direction, _x, _y)

# (Line 161) {// 불 생성 지역에, 있는 지형/폭탄 탐지
@EUDFunc
def CreateFire(fireRange, direction, _x, _y):
    # (Line 162) Map.SetMapXY(_x, _y, UnitID_Fire);
    Map.SetMapXY(_x, _y, UnitID_Fire)
    # (Line 163) for(var j=1; j<=fireRange; j++)
    j = EUDVariable()
    j << (1)
    if EUDWhile()(j <= fireRange):
        def _t2():
            j.__iadd__(1)
        # (Line 164) {
        # (Line 165) var x = _x;
        x = EUDVariable()
        x << (_x)
        # (Line 166) var y = _y;
        y = EUDVariable()
        y << (_y)
        # (Line 168) if(direction == 0)
        if EUDIf()(direction == 0):
            # (Line 169) {
            # (Line 170) if(x < j) x = 0;
            if EUDIf()(x >= j, neg=True):
                x << (0)
                # (Line 171) else x = x - j;
            if EUDElse()():
                x << (x - j)
                # (Line 172) }
            EUDEndIf()
            # (Line 173) if(direction == 1)
        EUDEndIf()
        if EUDIf()(direction == 1):
            # (Line 174) {
            # (Line 175) if(y < j) y = 0;
            if EUDIf()(y >= j, neg=True):
                y << (0)
                # (Line 176) else y = y - j;
            if EUDElse()():
                y << (y - j)
                # (Line 177) }
            EUDEndIf()
            # (Line 178) if(direction == 2)
        EUDEndIf()
        if EUDIf()(direction == 2):
            # (Line 179) {
            # (Line 180) if(x + j > row) x = row;
            if EUDIf()(x + j <= row, neg=True):
                x << (row)
                # (Line 181) else x = x + j;
            if EUDElse()():
                x << (x + j)
                # (Line 182) }
            EUDEndIf()
            # (Line 183) if(direction == 3)
        EUDEndIf()
        if EUDIf()(direction == 3):
            # (Line 184) {
            # (Line 185) if(y + j > col) y = col;
            if EUDIf()(y + j <= col, neg=True):
                y << (col)
                # (Line 186) else y = y + j;
            if EUDElse()():
                y << (y + j)
                # (Line 187) }
            EUDEndIf()
            # (Line 189) if (Map.GetMapXY(x, y) == UnitID_Wall) return;	// Imapssible
        EUDEndIf()
        if EUDIf()(Map.GetMapXY(x, y) == UnitID_Wall):
            EUDReturn()
            # (Line 190) else if (Map.GetMapXY(x, y) == UnitID_Fire) 	// Fire
        if EUDElseIf()(Map.GetMapXY(x, y) == UnitID_Fire):
            # (Line 191) Map.SetMapXY(x, y, UnitID_Fire);
            Map.SetMapXY(x, y, UnitID_Fire)
            # (Line 192) else if (Map.GetMapXY(x, y) == 0) 				// Empty
        if EUDElseIf()(Map.GetMapXY(x, y) == 0):
            # (Line 193) Map.SetMapXY(x, y, UnitID_Fire);
            Map.SetMapXY(x, y, UnitID_Fire)
            # (Line 194) else if (Map.GetMapXY(x, y) == UnitID_Box) 		// Breakable
        if EUDElseIf()(Map.GetMapXY(x, y) == UnitID_Box):
            # (Line 195) {
            # (Line 196) Map.SetMapXY(x, y, DeadBox);
            Map.SetMapXY(x, y, DeadBox)
            # (Line 197) return;
            EUDReturn()
            # (Line 198) }
            # (Line 199) else if (Map.GetMapXY(x, y) == DeadBox) return;
        if EUDElseIf()(Map.GetMapXY(x, y) == DeadBox):
            EUDReturn()
            # (Line 200) else 											// bomb (unitEpd)
            # (Line 201) {
        if EUDElse()():
            # (Line 202) const unitEpd = Map.GetMapXY(x, y);
            unitEpd = Map.GetMapXY(x, y)
            # (Line 203) Push(unitEpd);
            Push(unitEpd)
            # (Line 204) }
            # (Line 205) }
        EUDEndIf()
        # (Line 206) }
        EUDSetContinuePoint()
        _t2()
    EUDEndWhile()
    # (Line 208) function CreateItem(location)

# (Line 209) {
@EUDFunc
def CreateItem(location):
    # (Line 210) if(Helpers.GetRandom(0,2))// 0~1
    if EUDIf()(Helpers.GetRandom(0, 2)):
        # (Line 211) {
        # (Line 212) const randNum = Helpers.GetRandom(0, 9)%6; //0~8 -> 0~5
        randNum = Helpers.GetRandom(0, 9) % 6
        # (Line 213) CreateUnit(1, ItemList[randNum], location +1, Computer);
        DoActions(CreateUnit(1, ItemList[randNum], location + 1, Computer))
        # (Line 214) }
        # (Line 215) }
    EUDEndIf()
