## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *

def _IGVA(vList, exprListGen):
    def _():
        exprList = exprListGen()
        SetVariables(vList, exprList)
    EUDOnStart(_)

def _CGFW(exprf, retn):
    rets = [ExprProxy(None) for _ in range(retn)]
    def _():
        vals = exprf()
        for ret, val in zip(rets, vals):
            ret._value = val
    EUDOnStart(_)
    return rets

def _ARR(items):
    k = EUDArray(len(items))
    for i, item in enumerate(items):
        k[i] = item
    return k

def _SRET(v, klist):
    return List2Assignable([v[k] for k in klist])

def _SV(dL, sL):
    [d << s for d, s in zip(FlattenList(dL), FlattenList(sL))]

class _ATTW:
    def __init__(self, obj, attrName):
        self.obj = obj
        self.attrName = attrName

    def __lshift__(self, r):
        setattr(self.obj, self.attrName, r)

    def __iadd__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov + v)

    def __isub__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov - v)

    def __imul__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov * v)

    def __idiv__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov / v)

    def __iand__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov & v)

    def __ior__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov | v)

    def __ixor__(self, v):
        ov = getattr(self.obj, self.attrName)
        setattr(self.obj, self.attrName, ov ^ v)

class _ARRW:
    def __init__(self, obj, index):
        self.obj = obj
        self.index = index

    def __lshift__(self, r):
        self.obj[self.index] = r

    def __iadd__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov + v

    def __isub__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov - v

    def __imul__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov * v

    def __idiv__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov / v

    def __iand__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov & v

    def __ior__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov | v

    def __ixor__(self, v):
        ov = self.obj[self.index]
        self.obj[self.index] = ov ^ v

def _L2V(l):
    ret = EUDVariable()
    if EUDIf()(l):
        ret << 1
    if EUDElse()():
        ret << 0
    EUDEndIf()
    return ret

def _MVAR(vs):
    return List2Assignable([
        v.makeL() if IsEUDVariable(v) else EUDVariable() << v
        for v in FlattenList(vs)])

def _LSH(l, r):
    if IsEUDVariable(l):  return f_bitlshift(l, r)
    else: return l << r

## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY

# (Line 1) import Header;
import Header
# (Line 2) import Helpers;
import Helpers
# (Line 3) import Map;
import Map
# (Line 4) import Bomb;
import Bomb
# (Line 6) const scale						= Map.scale;
scale = _CGFW(lambda: [Map.scale], 1)[0]
# (Line 8) const Computer		 			= Header.Computer;
Computer = _CGFW(lambda: [Header.Computer], 1)[0]
# (Line 9) const UnitID_Civilian 			= Header.UnitID_Player[0];
UnitID_Civilian = _CGFW(lambda: [Header.UnitID_Player[0]], 1)[0]
# (Line 10) const UnitID_Tank 				= Header.UnitID_Player[2];
UnitID_Tank = _CGFW(lambda: [Header.UnitID_Player[2]], 1)[0]
# (Line 11) const UnitID_Goliath 			= Header.UnitID_Player[1];
UnitID_Goliath = _CGFW(lambda: [Header.UnitID_Player[1]], 1)[0]
# (Line 12) const UnitID_Bomb				= Header.UnitID_Bomb;
UnitID_Bomb = _CGFW(lambda: [Header.UnitID_Bomb], 1)[0]
# (Line 13) const UnitID_Fire				= Header.UnitID_Fire;
UnitID_Fire = _CGFW(lambda: [Header.UnitID_Fire], 1)[0]
# (Line 15) const ItemList					= Header.ItemList;
ItemList = _CGFW(lambda: [Header.ItemList], 1)[0]
# (Line 16) const Item_rangeUp				= Header.Item_rangeUp;
Item_rangeUp = _CGFW(lambda: [Header.Item_rangeUp], 1)[0]
# (Line 17) const Item_speedUp				= Header.Item_speedUp;
Item_speedUp = _CGFW(lambda: [Header.Item_speedUp], 1)[0]
# (Line 18) const Item_bombNUp				= Header.Item_bombNUp;
Item_bombNUp = _CGFW(lambda: [Header.Item_bombNUp], 1)[0]
# (Line 19) const Item_rangeMax				= Header.Item_rangeMax;
Item_rangeMax = _CGFW(lambda: [Header.Item_rangeMax], 1)[0]
# (Line 20) const Item_rideTank				= Header.Item_rideTank;
Item_rideTank = _CGFW(lambda: [Header.Item_rideTank], 1)[0]
# (Line 21) const Item_rideHide				= Header.Item_rideHide;
Item_rideHide = _CGFW(lambda: [Header.Item_rideHide], 1)[0]
# (Line 23) const EPD_Players	 			= EUDArray(6);
EPD_Players = _CGFW(lambda: [EUDArray(6)], 1)[0]
# (Line 24) const MaxRange					= 5;
MaxRange = _CGFW(lambda: [5], 1)[0]
# (Line 25) const MaxBomb					= 8;
MaxBomb = _CGFW(lambda: [8], 1)[0]
# (Line 26) const PlayerSpeed				= EUDArray(6);
PlayerSpeed = _CGFW(lambda: [EUDArray(6)], 1)[0]
# (Line 28) const loc0 		= $L('loc0');
loc0 = _CGFW(lambda: [GetLocationIndex('loc0')], 1)[0]
# (Line 29) const loc 		= $L('loc');
loc = _CGFW(lambda: [GetLocationIndex('loc')], 1)[0]
# (Line 30) const loc_p1 	= $L('p1');
loc_p1 = _CGFW(lambda: [GetLocationIndex('p1')], 1)[0]
# (Line 31) const loc_p2 	= $L('p2');
loc_p2 = _CGFW(lambda: [GetLocationIndex('p2')], 1)[0]
# (Line 32) const loc_p3 	= $L('p3');
loc_p3 = _CGFW(lambda: [GetLocationIndex('p3')], 1)[0]
# (Line 33) const loc_p4 	= $L('p4');
loc_p4 = _CGFW(lambda: [GetLocationIndex('p4')], 1)[0]
# (Line 34) const loc_p5 	= $L('p5');
loc_p5 = _CGFW(lambda: [GetLocationIndex('p5')], 1)[0]
# (Line 35) const loc_p6 	= $L('p6');
loc_p6 = _CGFW(lambda: [GetLocationIndex('p6')], 1)[0]
# (Line 37) const loclist	= [loc_p1, loc_p2, loc_p3, loc_p4, loc_p5, loc_p6];
loclist = _CGFW(lambda: [_ARR(FlattenList([loc_p1, loc_p2, loc_p3, loc_p4, loc_p5, loc_p6]))], 1)[0]
# (Line 39) function SetRangeAtBomb(unitEpd, range);
# (Line 40) function GetRangeAtBomb(unitEpd);
# (Line 41) function SetBombTimer(unitEpd, time);
# (Line 42) function GetCurrentBN(player);
# (Line 43) function GetBombNumber(player);
# (Line 44) function GetBombRange(player);
# (Line 45) function SetBombNumber(player, number);
# (Line 46) function SetBombRange(player, number);
# (Line 49) function SetPlayerEpd(player)
# (Line 50) {
@EUDFunc
def SetPlayerEpd(player):
    # (Line 51) EPD_Players[player] = epdread_epd(EPD(0x628438));
    _ARRW(EPD_Players, player) << (f_epdread_epd(EPD(0x628438)))
    # (Line 52) }
    # (Line 54) function GetPlayerEpd(player)

# (Line 55) {
@EUDFunc
def GetPlayerEpd(player):
    # (Line 56) return EPD_Players[player];
    EUDReturn(EPD_Players[player])
    # (Line 57) }
    # (Line 59) function InitPlayerLocation(player)

# (Line 60) {
@EUDFunc
def InitPlayerLocation(player):
    # (Line 61) var x, y;
    x, y = EUDCreateVariables(2)
    # (Line 62) if(player == 0) { x=1; y=1; }
    if EUDIf()(player == 0):
        x << (1)
        y << (1)
        # (Line 63) if(player == 1) { x=18; y=1; }
    EUDEndIf()
    if EUDIf()(player == 1):
        x << (18)
        y << (1)
        # (Line 64) if(player == 2) { x=1; y=11; }
    EUDEndIf()
    if EUDIf()(player == 2):
        x << (1)
        y << (11)
        # (Line 65) if(player == 3) { x=18; y=11; }
    EUDEndIf()
    if EUDIf()(player == 3):
        x << (18)
        y << (11)
        # (Line 66) if(player == 4) { x=1; y=6; }
    EUDEndIf()
    if EUDIf()(player == 4):
        x << (1)
        y << (6)
        # (Line 67) if(player == 5) { x=18; y=6; }
    EUDEndIf()
    if EUDIf()(player == 5):
        x << (18)
        y << (6)
        # (Line 69) const x2, y2 = Map.GetTileXY(x, y);
    EUDEndIf()
    x2, y2 = List2Assignable([Map.GetTileXY(x, y)])
    # (Line 70) Helpers.EUDSetLocation(loclist[player], x2, y2);
    Helpers.EUDSetLocation(loclist[player], x2, y2)
    # (Line 71) }
    # (Line 72) function InitPlayer(player)

# (Line 73) {
@EUDFunc
def InitPlayer(player):
    # (Line 74) SetPlayerEpd(player);
    SetPlayerEpd(player)
    # (Line 75) InitPlayerLocation(player);
    InitPlayerLocation(player)
    # (Line 76) CreateUnit(1, UnitID_Civilian, loclist[player]+1, player);
    DoActions(CreateUnit(1, UnitID_Civilian, loclist[player] + 1, player))
    # (Line 77) SetBombNumber(player, 1);
    SetBombNumber(player, 1)
    # (Line 78) SetBombRange(player, 1);
    SetBombRange(player, 1)
    # (Line 79) PlayerSpeed[player] = 1000;
    _ARRW(PlayerSpeed, player) << (1000)
    # (Line 80) if(Helpers.GetDeath(player, 216) == 0)
    if EUDIf()(Helpers.GetDeath(player, 216) == 0):
        # (Line 81) {
        # (Line 82) SetDeaths(player, SetTo, 1, 216);
        DoActions(SetDeaths(player, SetTo, 1, 216))
        # (Line 83) CenterView(loclist[player]+1);
        DoActions(CenterView(loclist[player] + 1))
        # (Line 84) }
        # (Line 85) }
    EUDEndIf()
    # (Line 86) function GetItem(player);

# (Line 87) function FollowLocation(player)
# (Line 88) {
@EUDFunc
def FollowLocation(player):
    # (Line 89) if(Command(player, AtLeast, 1, '(men)'))
    if EUDIf()(Command(player, AtLeast, 1, '(men)')):
        # (Line 90) MoveLocation(loclist[player]+1, '(men)', player, '20x13');
        DoActions(MoveLocation(loclist[player] + 1, '(men)', player, '20x13'))
        # (Line 91) }
    EUDEndIf()
    # (Line 92) function ItemCollect(player)

# (Line 93) {
@EUDFunc
def ItemCollect(player):
    # (Line 94) const item = GetItem(player);
    item = GetItem(player)
    # (Line 95) if(item != 0)
    if EUDIf()(item == 0, neg=True):
        # (Line 96) RemoveUnitAt(1, item, loclist[player]+1, Computer);
        DoActions(RemoveUnitAt(1, item, loclist[player] + 1, Computer))
        # (Line 97) }
    EUDEndIf()
    # (Line 99) function PlaceBomb(unitEpd)

# (Line 100) {
@EUDFunc
def PlaceBomb(unitEpd):
    # (Line 101) const player = Helpers.GetPlayerID(unitEpd);
    player = Helpers.GetPlayerID(unitEpd)
    # (Line 103) if(Helpers.GetBuildQueue1(unitEpd) == $U('Zerg Mutalisk'))
    if EUDIf()(Helpers.GetBuildQueue1(unitEpd) == EncodeUnit('Zerg Mutalisk')):
        # (Line 104) {
        # (Line 105) if(GetBombNumber(player) > GetCurrentBN(player))
        if EUDIf()(GetBombNumber(player) <= GetCurrentBN(player), neg=True):
            # (Line 106) {
            # (Line 107) const x, y = Map.GetTileIndex(unitEpd);
            x, y = List2Assignable([Map.GetTileIndex(unitEpd)])
            # (Line 108) const x2, y2 = Map.GetTileXY(x, y);
            x2, y2 = List2Assignable([Map.GetTileXY(x, y)])
            # (Line 109) Helpers.EUDSetLocation(loc, x2, y2);
            Helpers.EUDSetLocation(loc, x2, y2)
            # (Line 111) if(Map.GetMapXY(x,y) == 0)
            if EUDIf()(Map.GetMapXY(x, y) == 0):
                # (Line 112) {
                # (Line 113) const unitEpd = epdread_epd(EPD(0x628438));
                unitEpd_1 = f_epdread_epd(EPD(0x628438))
                # (Line 114) CreateUnit(1, UnitID_Bomb, loc +1, player);
                DoActions(CreateUnit(1, UnitID_Bomb, loc + 1, player))
                # (Line 115) Bomb.NewBomb(unitEpd);
                Bomb.NewBomb(unitEpd_1)
                # (Line 116) SetBombTimer(unitEpd, 10); 		// bomb timer
                SetBombTimer(unitEpd_1, 10)
                # (Line 117) const range = GetBombRange(player);
                range = GetBombRange(player)
                # (Line 118) SetRangeAtBomb(unitEpd, range); // Mark bomb range inside bomb
                SetRangeAtBomb(unitEpd_1, range)
                # (Line 119) }
                # (Line 120) }
            EUDEndIf()
            # (Line 122) Helpers.ResetBuildQueue(unitEpd);
        EUDEndIf()
        Helpers.ResetBuildQueue(unitEpd)
        # (Line 123) }
        # (Line 124) }
    EUDEndIf()
    # (Line 126) function SetBombTimer(unitEpd, time)

# (Line 127) {
@EUDFunc
def SetBombTimer(unitEpd, time):
    # (Line 128) SetMemoryEPD(unitEpd + 0x114/4, SetTo, time);
    DoActions(SetMemoryEPD(unitEpd + 0x114 // 4, SetTo, time))
    # (Line 129) }
    # (Line 130) function GetBombRange(player)

# (Line 131) {
@EUDFunc
def GetBombRange(player):
    # (Line 132) for(var i = 0; i<12; i++)
    i = EUDVariable()
    i << (0)
    if EUDWhile()(i >= 12, neg=True):
        def _t2():
            i.__iadd__(1)
        # (Line 133) if(Accumulate(player, Exactly, i, Gas))
        if EUDIf()(Accumulate(player, Exactly, i, Gas)):
            # (Line 134) return i;
            EUDReturn(i)
            # (Line 135) }
        EUDEndIf()
        EUDSetContinuePoint()
        _t2()
    EUDEndWhile()
    # (Line 136) function SetBombRange(player, number)

# (Line 137) {
@EUDFunc
def SetBombRange(player, number):
    # (Line 138) SetResources(player, SetTo, number, Gas);
    DoActions(SetResources(player, SetTo, number, Gas))
    # (Line 139) }
    # (Line 140) function GetCurrentBN(player)

# (Line 141) {
@EUDFunc
def GetCurrentBN(player):
    # (Line 142) for(var i = 0; i<12; i++)
    i = EUDVariable()
    i << (0)
    if EUDWhile()(i >= 12, neg=True):
        def _t2():
            i.__iadd__(1)
        # (Line 143) if(Command(player, Exactly, i, UnitID_Bomb))
        if EUDIf()(Command(player, Exactly, i, UnitID_Bomb)):
            # (Line 144) return i;
            EUDReturn(i)
            # (Line 146) }
        EUDEndIf()
        EUDSetContinuePoint()
        _t2()
    EUDEndWhile()
    # (Line 147) function GetBombNumber(player)

# (Line 148) {
@EUDFunc
def GetBombNumber(player):
    # (Line 149) for(var i = 0; i<12; i++)
    i = EUDVariable()
    i << (0)
    if EUDWhile()(i >= 12, neg=True):
        def _t2():
            i.__iadd__(1)
        # (Line 150) if(Accumulate(player, Exactly, i, Ore))
        if EUDIf()(Accumulate(player, Exactly, i, Ore)):
            # (Line 151) return i;
            EUDReturn(i)
            # (Line 152) }
        EUDEndIf()
        EUDSetContinuePoint()
        _t2()
    EUDEndWhile()
    # (Line 153) function SetBombNumber(player, number)

# (Line 154) {
@EUDFunc
def SetBombNumber(player, number):
    # (Line 155) SetResources(player, SetTo, number, Ore);
    DoActions(SetResources(player, SetTo, number, Ore))
    # (Line 156) }
    # (Line 158) function GetRangeAtBomb(unitEpd)

# (Line 159) {
@EUDFunc
def GetRangeAtBomb(unitEpd):
    # (Line 160) return dwread_epd(unitEpd + 0xFC/4);
    EUDReturn(f_dwread_epd(unitEpd + 0xFC // 4))
    # (Line 161) }
    # (Line 163) function SetRangeAtBomb(unitEpd, range)

# (Line 164) {//union offset(space for rally & psi)
@EUDFunc
def SetRangeAtBomb(unitEpd, range):
    # (Line 165) dwwrite_epd(unitEpd + 0xFC/4, range);
    f_dwwrite_epd(unitEpd + 0xFC // 4, range)
    # (Line 166) }
    # (Line 168) function GetItem(player)

# (Line 169) {
@EUDFunc
def GetItem(player):
    # (Line 170) for(var i=0; i<6; i++)
    i = EUDVariable()
    i << (0)
    if EUDWhile()(i >= 6, neg=True):
        def _t2():
            i.__iadd__(1)
        # (Line 171) {
        # (Line 172) const item = ItemList[i];
        item = ItemList[i]
        # (Line 173) if(Bring(Computer, AtLeast, 1, item, loclist[player]+1))
        if EUDIf()(Bring(Computer, AtLeast, 1, item, loclist[player] + 1)):
            # (Line 174) {
            # (Line 176) if(item == Item_rangeUp)
            if EUDIf()(item == Item_rangeUp):
                # (Line 177) {
                # (Line 178) const bombRange = GetBombRange(player);
                bombRange = GetBombRange(player)
                # (Line 179) if(bombRange < MaxRange)
                if EUDIf()(bombRange >= MaxRange, neg=True):
                    # (Line 180) {
                    # (Line 181) DisplayText("\x07[ Range + ]");
                    DoActions(DisplayText("\x07[ Range + ]"))
                    # (Line 182) SetBombRange(player, bombRange+1);
                    SetBombRange(player, bombRange + 1)
                    # (Line 183) return item;
                    EUDReturn(item)
                    # (Line 184) }
                    # (Line 185) return 0;
                EUDEndIf()
                EUDReturn(0)
                # (Line 186) }
                # (Line 188) if(item == Item_speedUp)
            EUDEndIf()
            if EUDIf()(item == Item_speedUp):
                # (Line 189) {
                # (Line 190) if(MemoryEPD(GetPlayerEpd(player) + 0x034 /4, AtMost, 1900) || PlayerSpeed[player] > 1900)
                if EUDIf()(EUDSCOr()(MemoryEPD(GetPlayerEpd(player) + 0x034 // 4, AtMost, 1900))(PlayerSpeed[player] <= 1900, neg=True)()):
                    # (Line 191) {
                    # (Line 192) DisplayText("\x07[ Speed + ]");
                    DoActions(DisplayText("\x07[ Speed + ]"))
                    # (Line 193) SetMemoryEPD(GetPlayerEpd(player) + 0x034 /4, Add, 100);
                    DoActions(SetMemoryEPD(GetPlayerEpd(player) + 0x034 // 4, Add, 100))
                    # (Line 194) PlayerSpeed[player] = PlayerSpeed[player] + 100;
                    _ARRW(PlayerSpeed, player) << (PlayerSpeed[player] + 100)
                    # (Line 195) return item;
                    EUDReturn(item)
                    # (Line 196) }
                    # (Line 197) return 0;
                EUDEndIf()
                EUDReturn(0)
                # (Line 198) }
                # (Line 200) if(item == Item_bombNUp)
            EUDEndIf()
            if EUDIf()(item == Item_bombNUp):
                # (Line 201) {
                # (Line 202) const bombNumber = GetBombNumber(player);
                bombNumber = GetBombNumber(player)
                # (Line 203) if(bombNumber < MaxBomb)
                if EUDIf()(bombNumber >= MaxBomb, neg=True):
                    # (Line 204) {
                    # (Line 205) DisplayText("\x07[ Bomb + ]");
                    DoActions(DisplayText("\x07[ Bomb + ]"))
                    # (Line 206) SetBombNumber(player, bombNumber+1);
                    SetBombNumber(player, bombNumber + 1)
                    # (Line 207) return item;
                    EUDReturn(item)
                    # (Line 208) }
                    # (Line 209) return 0;
                EUDEndIf()
                EUDReturn(0)
                # (Line 210) }
                # (Line 212) if(item == Item_rangeMax)
            EUDEndIf()
            if EUDIf()(item == Item_rangeMax):
                # (Line 213) {
                # (Line 214) const bombRange = GetBombRange(player);
                bombRange = GetBombRange(player)
                # (Line 215) if(bombRange < MaxRange)
                if EUDIf()(bombRange >= MaxRange, neg=True):
                    # (Line 216) {
                    # (Line 217) DisplayText("\x07[ Range ++ ]");
                    DoActions(DisplayText("\x07[ Range ++ ]"))
                    # (Line 218) SetBombRange(player, bombRange+2);
                    SetBombRange(player, bombRange + 2)
                    # (Line 219) return item;
                    EUDReturn(item)
                    # (Line 220) }
                    # (Line 221) return 0;
                EUDEndIf()
                EUDReturn(0)
                # (Line 222) }
                # (Line 224) if(item == Item_rideTank)
            EUDEndIf()
            if EUDIf()(item == Item_rideTank):
                # (Line 225) {
                # (Line 226) if(Command(player, Exactly, 1, UnitID_Civilian))
                if EUDIf()(Command(player, Exactly, 1, UnitID_Civilian)):
                    # (Line 227) {
                    # (Line 228) PlayerSpeed[player] = dwread_epd(GetPlayerEpd(player) + 0x034 /4);
                    _ARRW(PlayerSpeed, player) << (f_dwread_epd(GetPlayerEpd(player) + 0x034 // 4))
                    # (Line 229) RemoveUnit(UnitID_Civilian, player);
                    DoActions(RemoveUnit(UnitID_Civilian, player))
                    # (Line 230) SetPlayerEpd(player);
                    SetPlayerEpd(player)
                    # (Line 231) const chance = Helpers.GetRandom(0,2);
                    chance = Helpers.GetRandom(0, 2)
                    # (Line 232) if(chance == 1)
                    if EUDIf()(chance == 1):
                        # (Line 233) {
                        # (Line 234) CreateUnit(1, UnitID_Tank, loclist[player]+1, player);
                        DoActions(CreateUnit(1, UnitID_Tank, loclist[player] + 1, player))
                        # (Line 235) SetDeaths(player, SetTo, 1, UnitID_Tank);
                        DoActions(SetDeaths(player, SetTo, 1, UnitID_Tank))
                        # (Line 236) }
                        # (Line 237) else
                        # (Line 238) {
                    if EUDElse()():
                        # (Line 239) CreateUnit(1, UnitID_Goliath, loclist[player]+1, player);
                        DoActions(CreateUnit(1, UnitID_Goliath, loclist[player] + 1, player))
                        # (Line 240) SetDeaths(player, SetTo, 1, UnitID_Goliath);
                        DoActions(SetDeaths(player, SetTo, 1, UnitID_Goliath))
                        # (Line 241) }
                        # (Line 242) return item;
                    EUDEndIf()
                    EUDReturn(item)
                    # (Line 243) }
                    # (Line 244) return 0;
                EUDEndIf()
                EUDReturn(0)
                # (Line 246) }
                # (Line 247) if(item == Item_rideHide)
            EUDEndIf()
            if EUDIf()(item == Item_rideHide):
                # (Line 248) {
                # (Line 249) if(1)
                if EUDIf()(1):
                    # (Line 250) {
                    # (Line 254) DisplayText("\x07똥을 밟았다.");
                    DoActions(DisplayText("\x07똥을 밟았다."))
                    # (Line 255) return item;
                    EUDReturn(item)
                    # (Line 256) }
                    # (Line 257) return 0;
                EUDEndIf()
                EUDReturn(0)
                # (Line 259) }
                # (Line 260) }
            EUDEndIf()
            # (Line 261) }
        EUDEndIf()
        # (Line 262) }
        EUDSetContinuePoint()
        _t2()
    EUDEndWhile()
    # (Line 264) function OffRide(player)

# (Line 265) {
@EUDFunc
def OffRide(player):
    # (Line 266) if(Command(player, Exactly, 0, '(men)'))
    if EUDIf()(Command(player, Exactly, 0, '(men)')):
        # (Line 267) {
        # (Line 268) if(Helpers.GetDeath(player, UnitID_Tank) > 0 || Helpers.GetDeath(player, UnitID_Goliath) > 0)
        if EUDIf()(EUDSCOr()(Helpers.GetDeath(player, UnitID_Tank) <= 0, neg=True)(Helpers.GetDeath(player, UnitID_Goliath) <= 0, neg=True)()):
            # (Line 269) {
            # (Line 270) if(Bomb.boom == 0)
            if EUDIf()(Bomb.boom == 0):
                # (Line 271) {
                # (Line 272) SetPlayerEpd(player);
                SetPlayerEpd(player)
                # (Line 273) CreateUnit(1, UnitID_Civilian, loclist[player]+1, player);
                DoActions(CreateUnit(1, UnitID_Civilian, loclist[player] + 1, player))
                # (Line 274) SetMemoryEPD(GetPlayerEpd(player) + 0x034 /4, SetTo, PlayerSpeed[player]);
                DoActions(SetMemoryEPD(GetPlayerEpd(player) + 0x034 // 4, SetTo, PlayerSpeed[player]))
                # (Line 275) SetDeaths(player, SetTo, 0, UnitID_Tank);
                DoActions(SetDeaths(player, SetTo, 0, UnitID_Tank))
                # (Line 276) SetDeaths(player, SetTo, 0, UnitID_Goliath);
                DoActions(SetDeaths(player, SetTo, 0, UnitID_Goliath))
                # (Line 277) }
                # (Line 278) }
            EUDEndIf()
            # (Line 279) }
        EUDEndIf()
        # (Line 280) }
    EUDEndIf()
